[tool.poetry]
name = "modulo1"
version = "0.1.0"
description = ""
authors = ["Juan Cruz Lertora <juanclertora@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
